language: go

go:
  - 1.16.x
  - tip

before_install:
  - make
  - make test-setup

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
